name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run test script
        run: |
          chmod +x test.sh
          ./test.sh
